import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "../styles/globals.css";
import CustomThemeProvider from "../context/ThemeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CustomThemeProvider>
          <div className="flex flex-col min-h-screen">
            <header className="sticky top-0 w-full">
              <Navbar />
            </header>
            <main className="flex-1 scroll-smooth">{children}</main>
            <footer className="flex-1">
              <Footer />
            </footer>
          </div>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
